name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: echo "Running tests..."
    - name: Build project
      run: echo "Building the project..."
